const items = [
  {
    name: "Apple",
    price: 3.99,
    inStock: true,
    class: "fruit",
    img: "img/apple.webp",
    alt: "A bag of apples.",
  },
  {
    name: "Banana",
    price: 2.99,
    inStock: true,
    class: "fruit",
    img: "img/banana.png",
    alt: "A bunch of bananas.",
  },
  {
    name: "Mango",
    price: 7.99,
    inStock: true,
    class: "fruit",
    img: "img/mango.webp",
    alt: "A box of mangoes.",
  },
  {
    name: "Strawberry",
    price: 5.99,
    inStock: true,
    class: "fruit",
    img: "img/strawberry.png",
    alt: "A box of strawberries.",
  },
  {
    name: "Watermelon",
    price: 3.99,
    inStock: true,
    class: "fruit",
    img: "img/watermelon.png",
    alt: "A watermelon.",
  },

  {
    name: "",
    price: 3.99,
    inStock: true,
    class: "vegetables",
    img: "img/.png",
    alt: "A .",
  },

  {
    name: "Crab",
    price: 6.99,
    inStock: true,
    class: "seafood",
    img: "img/crab.png",
    alt: "A crab.",
  },
  {
    name: "Octopus",
    price: 8.99,
    inStock: true,
    class: "seafood",
    img: "img/octopus.png",
    alt: "A case of octopus.",
  },
  {
    name: "Tuna",
    price: 7.99,
    inStock: true,
    class: "seafood",
    img: "img/tuna.png",
    alt: "A tunafish.",
  },
  {
    name: "Yellowtail",
    price: 6.99,
    inStock: true,
    class: "seafood",
    img: "img/yellowtail.png",
    alt: "A crab.",
  },
  {
    name: "Crab",
    price: 6.99,
    inStock: true,
    class: "seafood",
    img: "img/crab.png",
    alt: "A crab.",
  },
  {
    name: "Lobster",
    price: 10.99,
    inStock: true,
    class: "seafood",
    img: "img/lobster.webp",
    alt: "A lobster.",
  },
  {
    name: "Sourdough bread",
    price: 6.99,
    inStock: false,
    class: "bread",
    img: "img/sourdough.webp",
    alt: "A loaf of sourdough bread.",
  },
  {
    name: "Baguette",
    price: 5.99,
    inStock: true,
    class: "bread",
    img: "img/baguette.png",
    alt: "A baguette.",
  },
  {
    name: "Pita bread",
    price: 5.99,
    inStock: true,
    class: "bread",
    img: "img/pita.webp",
    alt: "A stack of pita bread.",
  },
  {
    name: "White bread",
    price: 4.99,
    inStock: true,
    class: "bread",
    img: "img/whitebread.webp",
    alt: "A loaf of white bread.",
  },
  {
    name: "Brioche bread",
    price: 6.99,
    inStock: true,
    class: "bread",
    img: "img/brioche.webp",
    alt: "A loaf of brioche bread.",
  },
];
